List<Map<String, dynamic>> allProduct = [
  {
    'category': 'Casual Shirt',
    'categoryProduct': [
      {
        'name': 'Men\'s button up casual wear',
        'thumbnail':
            'https://m.media-amazon.com/images/I/61H-EYslpUL._UL1500_.jpg',
        'categoryname': 'casual shirt',
        'rating': 4.7,
        'ratingcount': 2229,
        'price': 399,
        'faceprice': 599,
        'discount': 12,
        'description':
            ' This enhanced stretch shirt provides maximum comfort and flexibility. Made with high-quality fabric, This shirt offers a tailored fit and modern design, perfect for any occasion.',
        'brand': 'KRIYONA',
        'color': 'c6 green',
        'fit': 'Regular fit',
        'style': 'Western',
        'size': [
          'M',
          'L',
          'XL',
          'XXL',
        ],
        'img': [
          'https://m.media-amazon.com/images/I/51p9Rb7VVnL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/71HaVBWBDjL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61Vf7kLb1lL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61H-EYslpUL._UL1500_.jpg',
        ],
        'quantity': 0,
      },
      {
        'name': 'Men\'s white casual wear',
        'thumbnail':
            'https://m.media-amazon.com/images/I/61tbE69D31L._UL1500_.jpg',
        'categoryname': 'casual shirt',
        'rating': 3.5,
        'ratingcount': 1587,
        'price': 429,
        'faceprice': 679,
        'discount': 7,
        'description':
            ' This enhanced stretch shirt provides maximum comfort and flexibility. Made with high-quality fabric, This shirt offers a tailored fit and modern design, perfect for any occasion.',
        'brand': 'KRIYONA',
        'color': 'white',
        'fit': 'Regular fit',
        'style': 'Western',
        'size': [
          'M',
          'L',
          'XL',
          'XXL',
        ],
        'img': [
          'https://m.media-amazon.com/images/I/617f46hgwrL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61pKkyTf7nL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61pKkyTf7nL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61tbE69D31L._UL1500_.jpg',
        ],
        'quantity': 0,
      },
      {
        'name': 'Men\'s purple casual wear',
        'thumbnail':
            'https://m.media-amazon.com/images/I/61T-dMfRkYL._SX679._SX._UX._SY._UY_.jpg',
        'categoryname': 'casual shirt',
        'rating': 3,
        'ratingcount': 799,
        'price': 369,
        'faceprice': 549,
        'discount': 23,
        'description':
            ' This enhanced stretch shirt provides maximum comfort and flexibility. Made with high-quality fabric, This shirt offers a tailored fit and modern design, perfect for any occasion.',
        'brand': 'KRIYONA',
        'color': 'purple',
        'fit': 'Regular fit',
        'style': 'Western',
        'size': [
          'M',
          'L',
          'XL',
          'XXL',
        ],
        'img': [
          'https://m.media-amazon.com/images/I/61J0gqzAcxL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61u5l-iPBgL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/51I79Tax1BL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61T-dMfRkYL._SX679._SX._UX._SY._UY_.jpg',
        ],
        'quantity': 0,
      },
      {
        'name': 'Men\'s pink casual wear',
        'thumbnail':
            'https://m.media-amazon.com/images/I/61QcIHGixAL._UL1500_.jpg',
        'categoryname': 'casual shirt',
        'rating': 3,
        'ratingcount': 799,
        'price': 799,
        'faceprice': 1899,
        'discount': 34,
        'description':
            ' This enhanced stretch shirt provides maximum comfort and flexibility. Made with high-quality fabric, This shirt offers a tailored fit and modern design, perfect for any occasion.',
        'brand': 'KRIYONA',
        'color': 'pink',
        'fit': 'Regular fit',
        'style': 'Western',
        'size': [
          'M',
          'L',
          'XL',
          'XXL',
        ],
        'img': [
          'https://m.media-amazon.com/images/I/61pHKqqicmL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61Q+mkJsZ5L._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/51xbTBGAiyL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/61QcIHGixAL._UL1500_.jpg',
        ],
        'quantity': 0,
      },
      {
        'name': 'Men\'s multicolor casual wear',
        'thumbnail':
            'https://m.media-amazon.com/images/I/71e2uJ0gtXL._UL1500_.jpg',
        'categoryname': 'casual shirt',
        'rating': 3.9,
        'ratingcount': 2971,
        'price': 699,
        'faceprice': 1659,
        'discount': 58,
        'description':
            ' This enhanced stretch shirt provides maximum comfort and flexibility. Made with high-quality fabric, This shirt offers a tailored fit and modern design, perfect for any occasion.',
        'brand': 'KRIYONA',
        'color': 'multicolor',
        'fit': 'Regular fit',
        'style': 'Western',
        'size': [
          'M',
          'L',
          'XL',
          'XXL',
        ],
        'img': [
          'https://m.media-amazon.com/images/I/711YhtQ77ZL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/71fHnjpEMlL._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/6120lFKhM0L._UL1500_.jpg',
          'https://m.media-amazon.com/images/I/71e2uJ0gtXL._UL1500_.jpg',
        ],
        'quantity': 0,
      },
    ],
  },
  {
    'category': 'T-shirt',
    'categoryProduct': [
      {
        'name': 'T Shirts for Men & Boys',
        'thumbnail':
            'https://m.media-amazon.com/images/I/715c1HNYIBL._UL1080_.jpg',
        'categoryname': 'casual shirt',
        'rating': 4.7,
        'ratingcount': 2229,
        'price': 399,
        'faceprice': 1199,
        'discount': 67,
        'description':
            'Oversized Loose Fit Relaxed Wide Fit Cotton Paisley Half Sleeves White Colour T-Shirt for Mens & Boys, Attractive Stylish Bandana Print Designed T Shirts for Men & Boys.',
        'brand': 'KRIYONA',
        'color': 'Navy Blue',
        'fit': 'Regular fit',
        'style': 'Western',
        'size': [
          'M',
          'L',
          'XL',
          'XXL',
        ],
        'img': [
          'https://m.media-amazon.com/images/I/611bsDHQdbL._UL1080_.jpg',
          'https://m.media-amazon.com/images/I/71fcPsXgxHL._UL1080_.jpg',
          'https://m.media-amazon.com/images/I/81Wuro0dxaL._UL1080_.jpg',
          'https://m.media-amazon.com/images/I/715c1HNYIBL._UL1080_.jpg',
        ],
        'quantity': 0,
      },
    ],
  },
];
